// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyW8KTJKBnSpGiHVcf28mJS4olivpYmUc',
    appId: '1:229484552631:web:b0301b3e050e6a40780832',
    messagingSenderId: '229484552631',
    projectId: 'event-planning-27758',
    authDomain: 'event-planning-27758.firebaseapp.com',
    storageBucket: 'event-planning-27758.firebasestorage.app',
    measurementId: 'G-7B231XP655',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD72q1HoI3oO7GwKoB1_8hyt9k_Wg97PWE',
    appId: '1:229484552631:android:5062ce2815e5abd5780832',
    messagingSenderId: '229484552631',
    projectId: 'event-planning-27758',
    storageBucket: 'event-planning-27758.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCizkjFLvxF2dxcf2Ugrpmsmoju_qONiIw',
    appId: '1:229484552631:ios:9fc64854ab8f00fb780832',
    messagingSenderId: '229484552631',
    projectId: 'event-planning-27758',
    storageBucket: 'event-planning-27758.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCizkjFLvxF2dxcf2Ugrpmsmoju_qONiIw',
    appId: '1:229484552631:ios:9fc64854ab8f00fb780832',
    messagingSenderId: '229484552631',
    projectId: 'event-planning-27758',
    storageBucket: 'event-planning-27758.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyW8KTJKBnSpGiHVcf28mJS4olivpYmUc',
    appId: '1:229484552631:web:bd964898729363c4780832',
    messagingSenderId: '229484552631',
    projectId: 'event-planning-27758',
    authDomain: 'event-planning-27758.firebaseapp.com',
    storageBucket: 'event-planning-27758.firebasestorage.app',
    measurementId: 'G-QSKN4L09KP',
  );
}
