abstract class AppRoutes {
  static const String splash = '/splash';
  static const String onBoarding = '/onboarding';
  static const String login = '/login';
  static const String register = '/register';
  static const String forgetPassword = '/forgetpassword';
  static const String verification = '/verification';
  static const String mainScreen = '/mainScreen';
  static const String home = '/home';
  static const String search = '/search';
  static const String favEvent = '/favEvent';
  static const String addEvent = '/addEvent';
  static const String favorite = '/favorite';
  static const String profile = '/profile';
  static const String details = '/details';
  static const String settings = '/settings';
  static const String changePassword = '/changePassword';
  static const String mapView = '/mapView';
  static const String emptyEvent = '/emptyEvent';
  static const String seeAllRecommendation = '/SeeAllRecommendation';
  static const String seeAllPopular = '/SeeAllPopular';
  static const String seeAllUpComing = '/SeeAllUpComing';
  static const String searchScreen = '/SearchScreen';
  static const String categoryEvents = '/categoryEvents/:id/:name';
  // static const String eventDetails = '/eventDetails/:id';
  static const String navBar = '/navigationBar';
  static const String editProfile = '/editProfile';
  static const String createEvent = '/createEvent';
}
